# Generated by Django 4.2.5 on 2023-10-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatquestion',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
