# Generated by Django 4.2.5 on 2023-10-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilotapp', '0002_chatquestion_response_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatquestion',
            name='response_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
