# Generated by Django 4.2.5 on 2023-10-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copilotapp', '0003_alter_chatquestion_response_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatquestion',
            old_name='response_data',
            new_name='response_json',
        ),
    ]
