# Generated by Django 4.2.5 on 2023-10-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilotapp', '0004_rename_response_data_chatquestion_response_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatquestion',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chatquestion',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
