// const serverurl = '/api/auth/';
export const API_URL = {
    loginURL: '/api/login/',
    registerUser: '/register/',
    getFiles :'/api/get_file_list/',
    getcolumnheaders :'/api/get_column_headers/',
    getcolumnvalues :'/api/get_column_values/',
    compareBatchWithGb :'/api/sel_batch_compare_with_gb_with_drill_down/',
    uploadfile :'http://localhost:8000/api/upload_file/',
    getBatches:'/api/get_batches/',
    getRecords:'/api/get_index/',
    getXAI: '/api/xai/',
    getCausalGraph: '/api/causal_graph_analysis/',
    // upload_file: '/api/upload_file/',
    getCtreatePrompt:'/api/create_prompt/',
    getHmiHistory :'/api/get_last_five_questions/',
    getWhatIFPredication :'/api/What_if/',
    getColumnRanges :'/api/get_column_ranges/',
    // getFolderList :'/api/get_folder_list/',
    // createFolder :'/api/create_folder/',
    // getFileList :'/api/get_file_list/',
    deleteFolder : '/api/delete_folder/',
    deleteFile : '/api/delete_files/',
    getFolderList: '/api/list_folders_for_user/',
    createFolder : '/api/create_folder_datalake/',
    getFileList :'/api/list_file_in_datalake/',
    upload_file: '/api/upload_file_to_blob/',
    getcolumnvalue: '/api/read-headers/',
    getrecipecolumnvalues: '/api/Get_Recipe/',
    getuniqueproduct: '/api/get_unique_products/'
}